docker push demorsys/rsys-platform-web-content-service:2.0-SNAPSHOT
docker push demorsys/rsys-platform-web-content-service:latest
docker push demorsys/rsys-platform-zipkin:2.0-SNAPSHOT
docker push demorsys/rsys-platform-zipkin:latest
docker push demorsys/rsys-platform-hystrix-dashboard:2.0-SNAPSHOT
docker push demorsys/rsys-platform-hystrix-dashboard:latest
docker push demorsys/rsys-platform-configuration:2.0-SNAPSHOT
docker push demorsys/rsys-platform-configuration:latest
docker push demorsys/rsys-platform-eureka:2.0-SNAPSHOT
docker push demorsys/rsys-platform-eureka:latest
docker push demorsys/rsys-platform-web-client:2.0-SNAPSHOT
docker push demorsys/rsys-platform-web-client:latest
docker push demorsys/rsys-platform-business-intelligence-service:2.0-SNAPSHOT
docker push demorsys/rsys-platform-business-intelligence-service:latest
docker push demorsys/rsys-platform-gateway:2.0-SNAPSHOT
docker push demorsys/rsys-platform-gateway:latest
docker push demorsys/rsys-platform-core:2.0-SNAPSHOT
docker push demorsys/rsys-platform-core:latest